### ISSUE TITLE
SimulationParameters essentially needed

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/QualificationPlan#107]
We need also the ability to inherit simulation parameters in version 7.5.

**Comment by msevestre** [comment]
Yeah that's not possible in 7.5. we'll have to reengineer everything that was implemented so far.

@yuri05

**Comment by msevestre** [comment]
Unless you mean "read simulation parameter out of the snapshot file". In that case, this is doable. But if the parameter is not in the snapshot, no chance

**Comment by Yuri05** [comment]
>>Unless you mean "read simulation parameter out of the snapshot file". In that case, this is doable. 

I think this should be always the case (@sfrechen please confirm)

**Comment by msevestre** [comment]
I will wait for @sfrechen confirmation that this is what he has in mind. If this is the case, we can try to implement

**Comment by sfrechen** [comment]
It's all about parameters with a formula that are overwritten in the simulation. I assume they are always part of the snapshot?!

**Comment by Yuri05** [comment]
>It's all about parameters with a formula that are overwritten in the simulation. I assume they are always part of the snapshot?!

Yes

**Comment by msevestre** [comment]
implemented here
https://github.com/Open-Systems-Pharmacology/PK-Sim/pull/1181
