### ISSUE TITLE
Why are properties required in PlotSettings?

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/QualificationPlan#112]
```
   "PlotSettings": {
          "type": "object",
          "properties": {
            "ChartWidth": {
              "$ref": "#/definitions/plotSize"
            },
            "ChartHeight": {
              "$ref": "#/definitions/plotSize"
            },
            "Fonts": {
              "type": "object",
              "properties": {
                "AxisSize": {
                  "$ref": "#/definitions/fontSize"
                },
                "LegendSize": {
                  "$ref": "#/definitions/fontSize"
                },
                "OriginSize": {
                  "$ref": "#/definitions/fontSize"
                },
                "WatermarkSize": {
                  "$ref": "#/definitions/fontSize"
                },
                "FontFamilyName": {
                  "type": "string",
                  "enum": [
                    "Arial",
                    "Tahoma",
                    "Times New Roman",
                    "Microsoft Sans Serif"
                  ]
                }
              },
              "required": [
                "AxisSize",
                "LegendSize",
                "OriginSize",
                "FontFamilyName",
                "WatermarkSize"
              ]
            }
          },
          "required": [
            "ChartWidth",
            "ChartHeight",
            "Fonts"
          ]
```

I think there should not be absolutely Font, or width or height don't you think? Similar to AxisSettings. All opt-in

**Comment by Yuri05** [comment]
In the axes settings all fields are mandatory.

**Comment by msevestre** [comment]
Not according to schema?

**Comment by Yuri05** [comment]
thx

Von: Michael Sevestre [mailto:notifications@github.com]
Gesendet: Donnerstag, 11. April 2019 13:42
An: Open-Systems-Pharmacology/QualificationPlan
Cc: Juri Solodenko; Assign
Betreff: Re: [Open-Systems-Pharmacology/QualificationPlan] Why are properties required in PlotSettings? (#112)


Not according to schema?

**Comment by Yuri05** [comment]
Yep, according to the schema.
* `Dimension `and `Unit `are [mandatory within `dimensionAndUnit`-type](https://github.com/Open-Systems-Pharmacology/QualificationPlan/blob/5b0eae7901409de8d13499edd42f1b349d4ecedd/schemas/OSP_Qualification_Plan_Schema.json#L329) 
* `GridLines `and `Scaling `are [mandatory within `axis`-type](https://github.com/Open-Systems-Pharmacology/QualificationPlan/blob/5b0eae7901409de8d13499edd42f1b349d4ecedd/schemas/OSP_Qualification_Plan_Schema.json#L356);
 `axis `inherits properties from `dimensionAndUnit`, thus those properties are also mandatory.
* `Type `is [mandatory within `axesXY`-type](https://github.com/Open-Systems-Pharmacology/QualificationPlan/blob/5b0eae7901409de8d13499edd42f1b349d4ecedd/schemas/OSP_Qualification_Plan_Schema.json#L380) (which inherits properties from axis and thus all axis-properties are mandatroy here)

I think it makes sense.

**Comment by msevestre** [comment]
I disagree. According to schema, AxesSettings properties are not mandatory

https://github.com/Open-Systems-Pharmacology/QualificationPlan/blob/master/schemas/OSP_Qualification_Plan_Schema.json#L586

Also the code in the Qualfiication Engine checks for each property before assigning it.
In a nutshell, you should not HAVE To define everything in a qualification plan according to me. What ever you define will take precedence over the default in Matlab

**Comment by Yuri05** [comment]
AxesSettings are [mandatory](https://github.com/Open-Systems-Pharmacology/QualificationPlan/blob/5b0eae7901409de8d13499edd42f1b349d4ecedd/schemas/OSP_Qualification_Plan_Schema.json#L977)

AxesSettings **for particular plot type** (your latest link from above) are not mandatory (because not all plot types are used in a qualification plan).
What I would like to achieve (but this is not possible on schema level: if a plot type is available in qualification plan, then axes settings **corresponding to this plot** type must be given)

**Comment by Yuri05** [comment]
Regarding the Plot Settings: it's different discussion for me, than axes settings.
Because for the axes settings there are either no defaults (dimension, unit), or it's pretty clear, what should be used (Scaling).
For the font settings there are defaults indeed, thus we could make some (all?) properties of PlotSettings optional.

**Comment by msevestre** [comment]
This is the title of the entry :) `Why are properties required in PlotSettings`
I think this is not helping consistency at all as people will be required to always define something!
