### ISSUE TITLE
Add option to specify symbol in DDIRatioPlots

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/QualificationPlan#123]
"Caption": "Itra+Mida (Mida iv)",
"Color": "#FF0000",
"Symbol": "Square",
....

**Comment by Yuri05** [comment]
per **Group**?

**Comment by sfrechen** [comment]
Currently, we do not plan to distinguish between single entries with in a group. Hence, yes!

In case, a user would like to differentiate between single entries, groups have to be set up accordingly.
