### ISSUE TITLE
pediatrics ratioplots: different symbols and colors options

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/QualificationPlan#149]
For pediatric ratio-plots:

Please make it also possible to create different symbols and colors for different studies and different compounds for 1 ratioplot! 

This is already possible for DDI-ratio plots....

@Yuri05 @sfrechen

**Comment by Yuri05** [comment]
Closing in favor of https://github.com/Open-Systems-Pharmacology/Reporting-Engine/issues/220
