### ISSUE TITLE
Error with MarkdownJoiner

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/QualificationPlan#160]
When I try to execute a qualification scenario in MatLab, I get the following error:

```
module.js:550 
    throw err; 
    ^ 
 
Error: Cannot find module '../../package.json' 
    at Function.Module._resolveFilename (module.js:548:15) 
    at Function.Module._load (module.js:475:25) 
    at Module.require (module.js:597:17) 
    at require (internal/module.js:11:18) 
    at Object.<anonymous> (c:\Program Files\Open Systems Pharmacology\Markdown_joiner\src\helpers\cli-helpers.js:2:17) 
    at Module._compile (module.js:653:30) 
    at Object.Module._extensions..js (module.js:664:10) 
    at Module.load (module.js:566:32) 
    at tryModuleLoad (module.js:506:12) 
    at Function.Module._load (module.js:498:3) 
```

Any idea what could have gone wrong?

**Comment by msevestre** [comment]
How did you install the markdown joiner? Can you actually start it?

**Comment by PavelBal** [comment]
I downloaded it from here https://github.com/Open-Systems-Pharmacology/QualificationPlan/releases/tag/v2.1 and just unpacked.

In the Matlab-script (based on https://github.com/Open-Systems-Pharmacology/Evaluation-plan-template/blob/master/Evaluation/Workflow.m), calling

`status = system(['"' MarkdownJoiner_path '" -i "' REOutput_path '" -o "' ReportOutput_path '"']);`

produces the above mentioned error.

**Comment by PavelBal** [comment]
This also happens when I try to execute the scirpt from https://github.com/Open-Systems-Pharmacology/Evaluation-plan-template

**Comment by msevestre** [comment]
can you go in your installation folder of markdown joiner in a terminal and simply call it?
what's the output?

Also maybe try this version instead?
https://ci.appveyor.com/api/buildjobs/j2mnisxqajt4xv5a/artifacts/markdown-joiner.zip

**Comment by PavelBal** [comment]
> can you go in your installation folder of markdown joiner in a terminal and simply call it?
what's the output?

Unable to generate markdown. Please provide input and output paths.

**Comment by msevestre** [comment]
ok so you can call it. 
Can you try to call it with the input folder generated by the reporting engine and a output folder?

markdown-joiner -i "path_input" -o "path_output"

**Comment by PavelBal** [comment]
OK what kind of sorcery is this? Calling 
`system(['"' MarkdownJoiner_path '" -i "' REOutput_path '" -o "' ReportOutput_path '"']);`

from Matlab results in an error, evaluating the expression and pasting the resulting string into cmd works!

**Comment by msevestre** [comment]
Sorry can't help here

**Comment by PavelBal** [comment]
As an additional information - somehow the call only works from PowerShell but not from cmd.
