### ISSUE TITLE
Multiple units in observed data file from advanced example

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/QualificationPlan#178]
![image](https://user-images.githubusercontent.com/18409098/123850715-58dfb400-d8e8-11eb-85bf-7a581709be8d.png)

What is the correct unit here?  This is from [here](https://github.com/Open-Systems-Pharmacology/QualificationPlan/blob/main/examples/advanced_01/reporting%20engine%20input/ObservedData/Chung%20et%20al.%202006%2C%20po%200.075%20mgkg%2C%20n%3D19.csv), but there are many other such cases.[](url)

**Comment by Yuri05** [comment]
assume [mg/l] here (last [ ] ). 
Was probably an issue with the previous observed data import
