### ISSUE TITLE
What is SectionLevel good for?

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/QualificationPlan#198]
@PavelBal @abdullahhamadeh @Yuri05 
Why are we using this? Does it ring a bell? I am adding it dynamically but I can't remember why

I had added the comment

>This is not part of the qualification plan. Rather this is some meta information that will be passed along to the Input processor to know at what level the input should be processed

**Comment by abdullahhamadeh** [comment]
I'm not 100% sure, but could it be the level of the 'tree' within a table of contents?  eg subunits come under DDI...

**Comment by Yuri05** [comment]
It was used for the proper indentation of created Input-Markdowns.
E.g. a compound building block is created like this
```
# Compound :XY
## Parameters
...
```
Section level 2 will shift all markdown headers by 2 and create
```
### Compound :XY
#### Parameters
...
```
Like [here](https://github.com/Open-Systems-Pharmacology/OSP-PBPK-Model-Library/blob/master/Alfentanil/alfentanil_evaluation_report.md#31-final-input-parameters)

**Comment by msevestre** [comment]
ok. good. Keeping it then :)
