### ISSUE TITLE
Check the section "Reference" field for validity

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/QualificationPlan#202]
Check that all "Reference" values in a qualification plan satisfy [HTML id naming rules](https://www.w3.org/TR/html4/types.html#type-id):
* The ID must start with a letter (a-z or A-Z)
* All subsequent characters can be letters, numbers (0-9), hyphens (-), underscores (_), colons (:), and periods (.)

```
      "Sections": [
        {
          "Reference": "invalid ref",
          "Title": "title"
        },
        {
          "Reference": "Valid_reference-example.1",
          "Title": "title"
        },
```

**Comment by msevestre** [comment]
ok let me define that regex of hell

**Comment by Yuri05** [comment]
my first idea was to allow lowcase letters only :)
In fact, we must assure that those anchors are supported in our reports on GitHub. From few things that I checked:
* starting with the number works
* spaces do not work
* special characters (§, $, %) do not work
* by the way, just checked that colon does not work as well!

so let's say:
* The ID must start with a letter (a-z or A-Z) **or a digit (0-9)**
* All subsequent characters can be letters, numbers (0-9), hyphens (-), underscores (_), ~colons (:),~ and periods (.)

**Comment by Yuri05** [comment]
Works for me:
![grafik](https://user-images.githubusercontent.com/25061876/165322373-18e6b818-02b1-4779-8860-dd2217ebca6d.png)

Maybe you tried to change the colour somewhere where we did not define any rule (e.g. PK-Sim plot settings export)?

**Comment by msevestre** [comment]
nope
![image](https://user-images.githubusercontent.com/1041237/165344809-81350177-2f3d-429e-a909-073cbc6d59c1.png)
