### ISSUE TITLE
Description of Input parameters in qualification Report

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/QualificationPlan#25]
For each PK-Sim simulation involved into a qualification scenario, the _Qualification Runner_ will export the table with all user defined parameters:

![grafik](https://user-images.githubusercontent.com/25061876/48080889-1032d400-e1ef-11e8-8e3a-fe09b625f93b.png)

Reporting Engine must combine all those tables into one User-Inputs table, where duplicates are removed and parameters are grouped by the building block type and by the building block.

Additionally, following information (which is not part of user defined parameter tables) will be exported:
* Calculation Methods used in every simulation
* Description of all building blocks/ simulations
* ... ?

**Comment by msevestre** [comment]
@Yuri05 Is this still what we want to do here? It does not seem to fit our  implementation at the moment
