### ISSUE TITLE
What should happen when the PKSim.CLI is given a configuration that is invalid?

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/QualificationPlan#30]
Typical arguments of the config at the moment
```
{
    "SnapshotPath": "C:\\projects\\QualificationPlan\\examples\\minimal\\input\\Intraconazole\\Intraconazole.json",
    "OutputFolder": "C:\\tests\\7.5\\Outputs",
    "BuildingBlocks": [{
        "Type": "Individual",
        "Name": "Ind",
        "SnapshotPath": "C:\\projects\\QualificationPlan\\examples\\minimal\\input\\Midazolam\\Midazolam.json"
    }]
}
```

At the moment and error is thrown if the snapshot file does not exist 

What should we do in the case that the individual to replace is not correct
1/ Either the snapshot file is not found
2/ Building block does not exist (Individual Ind) in the snapshot file (Midazolam)
3/The building block does not exist (Individual Ind) in the Intraconazole project. 

In my opinion, it's all not good and should lead to this specific export being canceled. Thoughts?

**Comment by Yuri05** [comment]
Exception.
If called by Qualification Runner: qualification plan consistensy should be checked before.
If called in oher context: CLI cannot execute.
So should be an exception in any case.

**Comment by msevestre** [comment]
>If called by Qualification Runner: qualification plan consistensy should be checked before.

The qualification runner cannot check that a building block exists in a project. It does not know anything about PKSim internals

**Comment by Yuri05** [comment]
then it would be good to have a `check `option in PKSim.CLI.
Which would not export anything, but just check passed configuration for validity and return `Valid/Invalid` plus what is invalid.
QualiRunner would check all project configurations first; if at least one is invalid - whole quali run should be cancelled.

**Comment by Yuri05** [comment]
Check `process.ExitCode` and if not ok return the path to the log file?

**Comment by msevestre** [comment]
I guess we could have the runner first call the cli with the check flag for all projects and somehow it would have to listen for return code of each. What is wrong would be logged into the log file and console. 

I would only do the basic checks because it takes time to load the project otherwise. Maybe it's not even worth it

**Comment by msevestre** [comment]
This is how a call is performed
https://github.com/Open-Systems-Pharmacology/InstallationValidator/blob/6464dc2b50f0f5dd6c87cd280d4dcf8dc8d39c74/src/InstallationValidator.Core/Services/BatchStarterTask.cs

>return the path to the log file?

Especially there is no way to return something other than the exit code.

The log file is an input parameter anyways so I don't think it matters ?

**Comment by Yuri05** [comment]
>The log file is an input parameter anyways so I don't think it matters ?

Yep, exit code should be enough then.

**Comment by msevestre** [comment]
ok cool
