### ISSUE TITLE
What files should be part of the reporting engine inputs?

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/QualificationPlan#67]
@Yuri05 I am just generating too much files at the moment which makes the diff in github useless
HEre is what is created for the advanced model
905MB of data, over 300 files, project files and snapshot file, for each simulation 
![image](https://user-images.githubusercontent.com/1041237/55039502-ba729300-4ffa-11e9-9d92-ab694f0e7ae4.png)

It feels that we really only need the results (csv, xls) file and the xml per simulation? Correct?
I don't think we need the project file

**Comment by Yuri05** [comment]
* per Simulation
  * xml
  * -Results.csv
* on the project level: nothing (currently .json and .pksim5 are exported)
* Observed data: CSV only
