### ISSUE TITLE
RE: Folder structure

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/QualificationPlan#7]
Here the RE folder structure (created by the _Qualification Runner_ after processing a Qualification Plan) is described.

* **_Inputs_**
  * RE Report configuration
  * Description of the qualification scenario (e.g. pdf)
  * **_Observed data_** (:arrow_right: EXTERNAL Observed data)
    * Observed data set 1 
    * ... 
    * Observed data set N
  * **_Project 1_**
    * **_Observed data_** (:arrow_right: INTERNAL Observed data)
      * Observed data set 1 
      * ... 
      * Observed data set N
    * **_Simulation 1_**
      * Simulation-XML
      * Population data (CSV) (POP simulations only)
      * Simulation results (if availabale)
      * Table with user defined parameters
    * **_Simulation 2_**
      * ...
  * **_Project 2_**
    * ...
* **_Report_**
  * **_Artifacts_** (:arrow_right: generated plots, tables etc.)
  * **_Qualification Report_** (e.g. pdf)
  * **_Qualification measures_** (:arrow_right: (machine readable) tables with qualification measures, e.g. csv)

**Comment by msevestre** [comment]
This has changed slightly but all in all, looks good. Closing
